CREATE TABLE CW1.TagTrailTable(
    TrailID INT,
    TagID INT,
    PRIMARY KEY(TrailID, TagID),
    FOREIGN KEY(TrailID) REFERENCES CW1.TrailTable(TrailID) ON DELETE CASCADE,
    FOREIGN KEY(TagID) REFERENCES CW1.TagTable(TagID) ON DELETE CASCADE
)