CREATE TABLE CW1.UserTable(
    UserID INT IDENTITY NOT NULL PRIMARY KEY,
    Username VARCHAR(32) NOT NULL UNIQUE,	-- Must be unique
    Email VARCHAR(64) NOT NULL UNIQUE,
    Pword VARCHAR(64) NOT NULL
)